---
name: Generate slides from source

on:                             # yamllint disable-line rule:truthy
  push:
    paths:
      - 'Content/Presentations/**'
      - 'Content/ReleaseBriefings/**'
  pull_request:
    branches: [ "main" ]
  # Allow running workflows manually:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        which: [Presentations, ReleaseBriefings]

    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: Install packages
      run: >
        sudo apt-get update &&
        sudo apt-get install -y --no-install-recommends
        make
        latexmk
        lmodern
        python3-pygments
        texlive
        texlive-luatex
        texlive-latex-extra
        texlive-plain-generic

    - name: Patch latexminted<0.7.1 for compatibility with python 3.14
      # See https://github.com/gpoore/minted/issues/463#issuecomment-4416201217
      run: >
        latexminted --version ||
        sudo apt -y install unzip wget dos2unix patch zip &&
        pushd /tmp &&
        unzip /usr/share/texlive/texmf-dist/scripts/minted/latexminted-*-py3-none-any.whl latexminted/cmdline.py &&
        wget https://patch-diff.githubusercontent.com/raw/gpoore/minted/pull/464.patch &&
        dos2unix latexminted/cmdline.py &&
        patch -p2 < 464.patch &&
        sudo zip -u /usr/share/texlive/texmf-dist/scripts/minted/latexminted-*-py3-none-any.whl latexminted/cmdline.py &&
        popd &&
        latexminted --version

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build slides
      run: >
        cd Content/${{ matrix.which }} &&
        make

    - name: Upload PDFs as artifacts
      id: deployment
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Slides${{ matrix.which }}
        path: |
          Content/${{ matrix.which }}/release-*.pdf
          Content/${{ matrix.which }}/modularized/*.pdf
